#!/bin/sh

# delete existing rules (in case of multiple runs of script)
bspc rule -r "*"
bspc monitor -d I II III IV V VI VII VIII IX X

# top padding matches size of bar, tight gaps + border for more space
bspc config top_padding 28
bspc config border_width 1
bspc config window_gap 2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    echo "dummy" > $startup_lock_file
fi
