xrdb -merge /home/tlowry/.config/Xresources &
fix_mon &
mpd &
run_polybar &
sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/bspwm &
exec bspwm
#sxhkd -c ~/.config/sxhkd/sxhkdrc &
#exec openbox-session
#exec jwm -f ~/.config/jwm/jwmrc
