# Common tasks
xrdb -merge /home/tlowry/.config/Xresources &
fix_mon &
mpd &
run_polybar &
# Uncomment next 2 lines for bspwm
sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/bspwm &
exec bspwm
# And the next 2 lines for openbox
#sxhkd -c ~/.config/sxhkd/sxhkdrc &
#exec openbox-session
