#!/bin/sh
[ -z "$1" ] && echo "use: clean_file_name <file_name>" && exit 1
file_name=`echo $1 | sed 's/ /_/g;s/.*/\L&/'`

[ -f "$file_name" ] || [ -d "$file_name" ] && echo "skip "$1" dest exists" ||  mv "$1" "$file_name"
