#!/bin/sh
[ -f "$1" ] || echo "use: docx2txt <document file>" || exit 1

# Replace all xml and output as plain text
unzip -p "$1" word/document.xml | sed -e 's/<\/w:p>/\n/g; s/<[^>]\{1,\}>//g; s/&gt/>/g; s/&lt/</g; s/[^[:print:]\n]\{1,\}//g'
