#!/bin/sh
# TODO: split gdrive path so it is always relative
[ -z $1 ] && echo "use: grm <gdrive file to rm>" && exit 1

[ -f $1 ] && cmd=delete || [ -d $1 ] && cmd=purge || echo "file doesn't exist" && exit 1
#echo $cmd $1
rclone $cmd gdrive:/$1 && rm -rf $1
