#!/bin/sh
[ -z "$3" ] && echo "use: mk_vm <name> <variant> <iso>" && exit 1
# example: mk_vm cent8 rhel8.1 /path/os/centos-8.1.1911-x86_64-dvd1.iso
virt-install \
--name "$1" \
--description "$1" \
--ram=4096 \
--vcpus=2 \
--os-type=Linux \
--os-variant="$2" \
--disk path=/var/lib/libvirt/images/"$1".qcow2,bus=virtio,size=20 \
--vnc \
--location "$3" \
--network bridge=br0  \
--extra-args ro
