#!/bin/sh
[ -z "$1" ] && echo "use: whirl <mv command>" && exit 1
to_move=()

# build list
for f in *;do
	new_name=`clean_file_name "$f"`
    if [ $new_name != "$f" ];then
        printf -v var "%q" "$f"
	    cmd="$1 "$var" $new_name"
	    to_move+=("$cmd")
    fi
done

for i in "${to_move[@]}"; do
	#echo "$i" >> cmd 
    $i
done
