# Common tasks
xrdb -merge /home/"$USER"/.config/Xresources &
fix_mon &
mpd &
run_polybar &
# Uncomment next 2 lines for bspwm
sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/bspwm &
exec bspwm
# common keybindings for any wm/de 
#sxhkd -c ~/.config/sxhkd/sxhkdrc &
# uncomment 1 line above and any de/wm of choice below
#exec openbox-session
